### ISSUE TITLE
Allow installing all packages at once instead of one-by-one

### ISSUE THREAD

**Issue by ob-ivan** [ob-ivan/diversitest#2]
Configuration example:

```yaml
package_manager:
    command_line: 'composer require {% for package, version in configuration %}{{ package }}:{{ version }}{% endfor %}'
    template_engine: 'twig' # OR 'shell' for $variable substitutions
    template_type: 'configuration' # OR 'package' for old behavior
```

Bonus: Hardcode parameters for often used package managers such as composer, npm/yarn.

```yaml
package_manager: composer
```
