### ISSUE TITLE
Allow choosing a PHP executable per configuration

### ISSUE THREAD

**Issue by ob-ivan** [ob-ivan/diversitest#23]
We may have different configurations for different PHP versions, as it is done in this project's own `diversitest.yaml`:

```yaml
package_manager: 'composer'
test_runner: 'vendor/bin/phpunit'
configurations:
    php-5:
        symfony/console: ^3.0
        symfony/process: ^3.0
        symfony/yaml: ^3.0
        twig/twig: ^1.0
    php-7:
        symfony/console: ^4.0
        symfony/process: ^4.0
        symfony/yaml: ^4.0
        twig/twig: ^2.0
```

If multiple PHP executable versions are present on the machine, we need to be able to configure that.

For example, like this:

```yaml
configurations:
    php-5:
        php: php5.5
        symfony/console: ^3.0
        symfony/process: ^3.0
        symfony/yaml: ^3.0
        twig/twig: ^1.0
    php-7:
        php: php7.4
        symfony/console: ^4.0
        symfony/process: ^4.0
        symfony/yaml: ^4.0
        twig/twig: ^2.0
```
