### ISSUE TITLE
Allow to define configurations rather than individual packages

### ISSUE THREAD

**Issue by ob-ivan** [ob-ivan/diversitest#6]
A configuration is a set of packages with fixed version specifications. For example, this config:

```yaml
packages:
    alice: [1, 2]
    bob: [3, 4]
```

defines four configurations:
- alice:1 bob:3
- alice:1 bob:4
- alice:2 bob:3
- alice:2 bob:4

Some configurations may turn out useless, e.g. if some packages are mutually exclusive (say, `alice:2` and `bob:4`), or the total number of configurations may turn out too large, and we don't want to waste our time on running tests with them.

We need a way to define a limited set of configurations without multiplying all by all.

An example config file would be:

```yaml
configurations:
    config_1:
        alice: 1
        bob: 3
    config_2:
        alice: 1
        bob: 4
    config_3:
        alice: 2
        bob: 3
```

As to `packages` and `configurations` keys compatibility, we can start with declaring them mutually exclusive. If this proves insufficient, we can think of multiplying packages by configurations later.
